### ISSUE TITLE
Queries 

### ISSUE THREAD

**Issue by msehabibur** [WMD-group/TrapLimitedConversion#1]
Hi, can I possibly know the meaning of 1 in the following snippet? "V_Zn  3  1" Please see the snapshot. Also, for example, in "0  1.41538  1", I understand the first and second entries are q and defect formation energy at zero fermi level, or VBM, but can I know interpretation of third entries that is "1"? 
<img width="428" alt="Screenshot 2024-04-12 at 4 40 24 PM" src="https://github.com/WMD-group/TrapLimitedConversion/assets/96934016/b3df3a23-7515-4d5c-8651-6dd848af75dd">

**Comment by msehabibur** [comment]
Another question, can you please explain why, for some defects, the hole capture coefficient is 1, while for others it is zero?Can you please explain Sn_Zn (+1/+2) for example? 
<img width="686" alt="Screenshot 2024-04-12 at 4 44 14 PM" src="https://github.com/WMD-group/TrapLimitedConversion/assets/96934016/3125b1ed-3745-4d9b-963d-799c9fd4b27f">

**Comment by xw-w** [comment]
Hi! 

- The `input-fermi.dat` file is sourced from the [sc-fermi](https://github.com/jbuckeridge/sc-fermi/tree/master) package and follows the same format. Specifically:
  - The first line indicates whether system is spin polarised or not (1 = non-spin polarised; 2 = spin polarised)
  - The number in the third column is the degeneracy term which refers to the number of possible electron configurations for a defect in a particular charge state, including spin degeneracy and geometry degeneracy
 
- For the question of capture coefficients, although we recommend you to input the actual calculated capture coefficients, sometimes you may want to simplify the procedure:
  - Since the trap-limited efficiency of the entire system is limited by the transition with the largest capture coefficient, you may put 0 if the capture process of a certain defect has a negligible effect
  - Within a single transition, the capture is always limited by the slower process (whether electron or hole capture). So you may put 1 if the certain capture process is extremely fast
